export enum MotivoDenuncia {
  CONTEUDO_INAPROPRIADO = "CONTEUDO_INAPROPRIADO",
  SPAM = "SPAM",
  DISCURSO_DE_ODIO = "DISCURSO_DE_ODIO",
  ASSÉDIO = "ASSÉDIO",
  VIOLENCIA = "VIOLENCIA",
  DESINFORMACAO = "DESINFORMACAO",
  FRAUDE = "FRAUDE",
  VIOLACAO_DE_DIREITOS_AUTORAIS = "VIOLACAO_DE_DIREITOS_AUTORAIS"

}
